version: '3'

services:
  web:
    image: emfarih/portfolio-blockchain-solana:v1.2
    container_name: blockchain_solana
    restart: unless-stopped
    expose:
      - "80"  # allows internal access for 'proxy'

  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # this is the only container exposing host port 80
    depends_on:
      - web
